export const randomPaletteNames = [
    "Leonardo's Special",
    "Funky Fresh",
    "Pixel Perfect",
    "HueTastic",
    "Color Crazy",
    "ShadeWave",
    "Picasso Party",
    "Shade of Thrones",
    "Indiana Tones",
    "Da Vinci Deco",
    "Fifty Shades of Shade",
    "Shady Gaga",
    "Game of Tones",
    "Breaking Bad Blues",
    "Mulan Rouge",
    "Pastel Parade",        
    "Galactic Glow",        
    "Technicolor Tango",    
    "Hipster Hues",         
    "Retro Radiance",
    "Beachy Blues",
    "Neon Nights",
    "Chic Chroma",
    "Crayon De La Crème",
    "Bond... James Bondi Blue",
    "Stranger Tints",
    "Jazzberry Jam",
    "Samba Sunsets",
    "Cinematic Citrus",
    "Punk Picasso",
    "Mandalorian Metallics",
]